redis:
  image: redis
  restart: always
  container_name: redis7001
  command: redis-server --requirepass redis7001
  ports:
    - "7001:6379"

browserless:
    image: browserless/chrome:latest
    restart: always
    ports:
      - 4001:3000
    environment:
      # MAX_CONCURRENT_SESSIONS是控制浏览器并发度的
      - CONNECTION_TIMEOUT=180000
      - MAX_CONCURRENT_SESSIONS=10
      - PREBOOT_CHROME=true
      - KEEP_ALIVE=true